name: hello-world
on: push
job:
  hello-world-job:
    runs-on: ubuntu-lastest
    steps:
      - names: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"  
